### PR TITLE
soAnimCmdModuleImpl and soColorBlendModuleImpl

### PR DESCRIPTION
**Pull request by WispSSBM**
There's a few different things here:

- soColorBlendModule and mappings. Tested with my own code that uses them.
- soAnimCmdModule
     - This one is only partially finished, there are one or two classes that have weird layouts. Still, I was able to
        read a fighter's animCmd set with them, so I wanted to put it out as a starting point for future work and document
        what I found.
- Split related event observers into their own files as mentioned by code comments in the base observer header.
- Document some reverse engineering of fields and functions on ms::CharWriter.

### CODE REVIEW

**Comment by ilazoja** [comment]
Oh hype hype, great stuff

I think the missing key to soAnimCmdInterpreter is that it inherits acCmdInterpreter based on looking at its constructor, tho it is extremely strange that it didn't show up in the RTTI, first time I've seen that.

Only other thing is that we avoid capitalizing enums so that they don't get confused with macros, so the enums in soAnimCmdArgumentType should be Anim_Cmd_Arg_Int for example

**Comment by WispSSBM** [comment]
Really? Not `AnimCmdArgInt`? I'll change it if that's right though. For the acAnimCmdInterpreter stuff I'll add it if it works out, but I probably won't have too much time to come back to it in the super near future if it winds up being a rabbit hole to go down.

**Comment by ilazoja** [comment]
Other enums currently in the repo currently look like Fighter_Donkey for example. So the general nomenclature is as long as the name of the value follows an underscore. So AnimCmdArg_Int could work, or AnimCmd_Arg_Int. Up to you though how you want it specifically, tho personally I'd probs go for the latter. 

And sounds good! I don't think it should be too much of a rabbit hole since it's only one level of inheritance, but if it ends up being too much trouble then no worries, can just leave a note about its inheritance in that case.

**Comment by WispSSBM** [comment]
Should be good to merge now, I looked at acCmdInterpreter and it was actually bigger than soAnimCmdInterpreter, so I'm not sure what the relationship is between the two of them. Left a comment about it for whoever winds up looking at it next.

**Pull request merged**
