### PR TITLE
gfPadStatus Implementation

### PR DESCRIPTION
**Pull request by WispSSBM**
Not too much to say about this one, this is the lower-level pad structure that the game reads every frame in `gfPadSystem::updateSystem`. This was somewhat implemented in Fracture's setup, and was documented a little more in Eon's implementation of the P+ debug menu code. I've used this header in my own code and I think it's accurate.

### CODE REVIEW

**Comment by ilazoja** [comment]
Looks great! Super glad this was documented since it's very useful! Only thing is if those enums could use the convention so that they don't get confused with macros. e.g. GF_PAD_ERROR_NONE -> Gf_Pad_Error_None

**Comment by ilazoja** [comment]
Oh also really small thing but if _substick_ could be _subStick_ too for consistency cause that's how it's written in the symbols and in so_controller_impl.h

**Comment by Sammi-Husky** [comment]
Are there other instances where we have enums using casing like that? (Gf_Pad_Error_None).

Typically, i prefer enums all uppercase if possible. `HeapType` is different only because it matches what is in the in game logs so it makes it familiar and easy to understand.

What i would do is try and copy what we have for the HeapType enum and wrap the enum declaration in a namespace. and then simplify the names. 

e.g:
```
namespace gfPadError {
  enum PadError {
      NONE = 0,
      NO_CONTROLLER = -1,
      NOT_READY =  -2,
      TRANSFER = -3
  };
}
```
When done this way, people will reference the enum like this: `gfPadError::NONE` which is much more concise and readable anyways.

**Comment by ilazoja** [comment]
In some cases we do have it kinda like that at the moment, like for ftKind, the names are Fighter_Mario for example. I think your formatting works great tho, as long as it's distinguishable from a macro then it's chill aha

**Comment by WispSSBM** [comment]
Sorry I left this sitting so long; I addressed your comments and things should be good to go. :+1:

**Comment by Sammi-Husky** [comment]
Looks good thanks for this!!!!

**Pull request merged**
