### PR TITLE
Add module.h, update RSBE01.lst and other headers to support st_otrain

### PR DESCRIPTION
**Pull request by mparisi20**
I updated the headers and symbol map to help match st_otrain.rel. This includes inlining some of the virtual member functions in stMelee and Stage, which causes them to be emitted to the REL.

### CODE REVIEW

**Comment by ilazoja** [comment]
Looks good! although maybe the StageKind enum should be in stage.h? As well as I think we should avoid all caps for the enum value names since that can be confused with macros.

**Comment by ilazoja** [comment]
Awesome, also ig last thing. Maybe the namespace should be called srStageKind since that's what it seems to be called officially in the game? And was thinking probs to drop the Stage_ prefix since it's not neccessary with the namespace and have the names be Pascal Case.

**Comment by mparisi20** [comment]
Ok, I wasn't sure if we were dropping the "sr" prefix, since [memory.h](https://github.com/Sammi-Husky/BrawlHeaders/blob/main/Brawl/Include/memory.h) defines `HeapType` even though the symbol maps call it `srHeapType`. But I can make the change either way.

**Comment by ilazoja** [comment]
Ah good point. I think we should probs keep the sr prefix since there appears to be two StageKinds, srStageKind and muStageKind

**Comment by Sammi-Husky** [comment]
LGTM. After updating it to `srStageKind` i'll merge this in. 

For `HeapType`, you are right that it should be called `srHeapType` as well. i hadn't seen those symbols at the time i created the repo, and `HeapType` was just about the first thing i created so it makes sense that i missed that.

As a general rule, we are trying to match everything to the same structure and naming scheme as the Brawl devs so if you see anything else like that, feel free to correct it as well.

**Comment by mparisi20** [comment]
Should be OK now. Too bad we don't have `enum class` to avoid global namespace pollution without needing to make our own namespace, though.

**Pull request merged**
